name    'rbabu-tomcat7single'
version '0.1.0'
source ''
author 'rbabu'
license 'Apach 2.0'
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
